feat : 온보딩 페이지 구현
Programmers-HandsUp/FE-HandsUp pull request #101
Opened 2024-03-01 09:28 UTC by JuJangGwon

## 📑 구현 사항
###  온보딩 페이지 구현
https://github.com/Programmers-HandsUp/FE-HandsUp/assets/40955023/ec58ed1e-cd0d-4002-acdd-b990cb1cf3df

## 🚧 특이 사항

-

## 📃 참고 자료

- 

## 🚨 관련 이슈
close #62

2024-03-02 07:17 UTC, oridori2705 requested changes
장권님 고생하셨습니다!
Funnel을 구현하신 점 존경스럽습니다!
나중에 저도 장권님 코드를 참고해서 배우겠습니다!!

2024-03-02 07:17 UTC, oridori2705 commented on src/app/_component/common/ProgressBar/ProgressBar.variants.ts
> +export const ProgressBarVariants = cva("", {
cva가 객체라서 파스칼케이스 보다는 카멜케이스나 스네이크 케이스를 추천드립니다!
저는 보통 카멜케이스로 `progressBarVariants`같이 작성합니다!

2024-03-02 07:17 UTC, oridori2705 commented on src/app/onboarding/component/SignupHeader.tsx
> +        percent={getProgressbarPercentage()}
위 코드를 아래와 같이 바꿔도 좋을 것 같아요!
```
  const pagePercentages = [20, 50, 75, 100];
  const progressBarPercentage = pagePercentages[nowPage] || 100;
  
  ...

     percent={progressBarPercentage}
``

2024-03-02 07:17 UTC, oridori2705 commented on src/app/onboarding/component/funnel/FinishFunnel.tsx
> +
아하 isLoading이 필요한 부분인가요??
로직을 자세히는 잘 모르겠지만 api요청시 react query를  사용하면 isPending과 같은 데이터가 제공되니까 그걸 사용하시는 건가요??

2024-03-02 17:08 UTC, imssein reviewed
장권님 고생하셨습니다!

2024-03-02 17:08 UTC, imssein commented on src/utils/onGetImageFile.tsx
> +  const fileInput = document.createElement("input");
이미지 업로드를 리액트 컴포넌트의 상태와 이벤트 핸들러를 이용하지않고, DOM API를 사용한 이유가 궁금합니다! 👀

2024-03-05 03:27 UTC, JuJangGwon commented on src/app/onboarding/component/funnel/FinishFunnel.tsx
> +
아 네 업로드 부분을 useMutation 사용예정인데, 해당 부분은 useMutation훅의 isLoading 기능을 사용 예정입니다

2024-03-05 04:19 UTC, JuJangGwon commented on src/app/onboarding/component/SignupHeader.tsx
> +        percent={getProgressbarPercentage()}
오홍이 좋습니다!

2024-03-05 07:08 UTC, JuJangGwon commented on src/utils/onGetImageFile.tsx
> +  const fileInput = document.createElement("input");
현재 프로젝트에 이미지 불러오기 버튼이 들어갈 부분이 많은데 매번 해당 기능이 필요할 때마다 input을 만들고 숨긴 후 버튼과 ref을 연결해서 이벤트 처리하는 방법이 번거로울 거 같아서 onGetImageFile 함수 호출 시 함수 내에서 input 생성하고 저장된 파일을 콜백함수로 넘길 수 있도록 추상화해봤습니다. 이때 함수 내에서 input을 생성해야 하기 때문에 DOM APi를 이용했습니다.

2024-03-05 07:11 UTC, JuJangGwon commented on src/utils/onGetImageFile.tsx
> +  const fileInput = document.createElement("input");
input이 onGetImageFile함수내에서 만들어지기 때문에 리액트 컴포넌트의 상태나 이벤트 핸들러가 따로 필요없더라구요

2024-03-05 16:44 UTC, oridori2705 approved these changes

2024-03-07 08:43 UTC, merged