feat : 로그인 페이지 구현
Programmers-HandsUp/FE-HandsUp pull request #102
Opened 2024-03-01 10:20 UTC by JuJangGwon

## 📑 구현 사항

### 로그인 페이지 구현

https://github.com/Programmers-HandsUp/FE-HandsUp/assets/40955023/7daa596b-7765-4de0-86c2-12ba3ece91dd

<br/> 

- [x] 로그인 페이지 기능 구현
- [x] MSW 로그인 모킹 APi 구현 
  * msw 로그인시 refresh token(헤더 - 쿠키에 전송) / access token(request- body) 
  * refresh Token - 쿠키 저장 / access Token - 로컬 스토리지 저장

## 🚧 특이 사항

## 🚨 관련 이슈

close #85

2024-03-02 07:22 UTC, oridori2705 requested changes
장권님 고생하셨습니다!

2024-03-02 07:22 UTC, oridori2705 commented on src/app/login/component/SocialLoginContainer.tsx
> +        </button>
네이버와 구글 버튼의 배경색은 초록색과 흰색으로 해도 괜찮을 것 같아서 개인적으로 의견 남깁니다!
보통 사이트의 로그인 버튼처럼 말이죠...ㅎㅎ

2024-03-02 07:22 UTC, oridori2705 commented on src/utils/mocks/api/authApis.ts
> +  http.post("http://localhost:9090/api/login", async ({ request }) => {
저는 /api/~ 로 했었는데 혹시 무슨 문제가 있었나요??

2024-03-02 17:16 UTC, imssein reviewed
장권님 고생하셨습니다!

2024-03-02 17:16 UTC, imssein commented on src/app/hooks/queries/useAuth.ts
> +    mutationFn: async (authForm: LoginFormValues) => await setLogin(authForm),
저는 mutaionFn은 이미 promise를 반환하는 비동기 함수를 기대하고 있어 async/await 작성을 따로 안했어요! 
장권님은 어떻게 생각하시나요? ?

2024-03-05 07:14 UTC, JuJangGwon commented on src/app/login/component/SocialLoginContainer.tsx
> +        </button>
좋습니다 당장 변경하도록하죠!

2024-03-05 07:15 UTC, JuJangGwon commented on src/utils/mocks/api/authApis.ts
> +  http.post("http://localhost:9090/api/login", async ({ request }) => {
9090포트로 Mock 서버가 열려서 http://localhost:9090로 fetch 경로를 잡았습니다!

2024-03-05 07:21 UTC, JuJangGwon commented on src/app/hooks/queries/useAuth.ts
> +    mutationFn: async (authForm: LoginFormValues) => await setLogin(authForm),
앗 ... 따로 작성을 안해도되는군요? 좋은 지적 감사합니다

2024-03-05 16:46 UTC, oridori2705 approved these changes

2024-03-05 18:35 UTC, merged