feat : 회원 가입 페이지 기능 구현
Programmers-HandsUp/FE-HandsUp pull request #103
Opened 2024-03-01 10:46 UTC by JuJangGwon

## 📑 구현 사항

### 회원 가입 페이지 기능 구현 

https://github.com/Programmers-HandsUp/FE-HandsUp/assets/40955023/daa603e2-2a09-47f1-9cf2-c2492c4686e0

<br/> 

- [x] 회원 가입 페이지 기능 구현
- [x] MSW- 회원 가입 모킹 APi 구현
  *  아이디 중복검사 api
  * 회원 가입 api (+ JWT 토큰 발급 기능 구현)

## 🚨 관련 이슈

close #86

## 📑 리뷰 반영사항
- [x] api 함수들 반환 타입 any에서 관련 타입들로 변경 
- [x] api 함수들 내부에 있는 Api response 값 저장 변수들 이름 변경 (기존 req -> response로 변경)
- [x] 아이디, 비밀번호 입력 input에 좌측 여백 추가 
- [x] 기존에는  auth관련 mutation 함수들을 모두 utils/queres/useAuth.ts에서 관리하는 방법에서 utils/mutation/use(mutation함수명).ts 형식으로 한 mutation 폴더내에 한 mutation당 하나의 파일로 관리하는 방법으로 변경

2024-03-02 07:30 UTC, oridori2705 requested changes
장권님 고생하셨습니다!
로그인 페이지와 비슷해서 간단하게 리뷰해봤습니다!

2024-03-02 07:30 UTC, oridori2705 commented on src/app/api/auth.ts
> +  const req = await fetch("http://localhost:9090/api/login", {
저는 보통 fetch로 받는 데이터 변수명은 res나 response로 하곤했습니다!
fetch로 서버에 데이터를 요청 후에 "응답" 한다라고 생각했습니다!

2024-03-02 07:30 UTC, oridori2705 commented on src/app/signup/SignupForm.tsx
> +  };
class-variance-authority를 쓰셔도 좋을 것 같아요!

2024-03-02 11:40 UTC, hj9118 requested changes

2024-03-02 11:40 UTC, hj9118 commented on src/app/login/component/EmailLoginForm.tsx
> +          <Input.InputInnerBox className="w-[13.2rem] h-[2.6rem] text-black">
아이디, 비밀번호에 좌측으로 여백이 조금 있으면 좋겠다는 생각이 있어요! 하단에 소셜로그인 버튼은 약간의 여백이 있는데 인풋의 경우는 조금 타이트하다는 느낌이 있는 것 같습니다

2024-03-02 17:25 UTC, imssein reviewed
장권님 고생하셨습니다!

2024-03-02 17:25 UTC, imssein commented on src/app/hooks/queries/useAuth.ts
> +export function useSignUp() {
저희 프로젝트 폴더 구조를 useQuery는 queries폴더, useMutation은 mutations폴더 이렇게 생각했어요! 
또 저는 한 파일에 하나의 query나 mution들을 작성했는데,  장권님은 도메인별로 한 파일에 모아서 작성하셨군요!! 이부분 팀원들분과 얘기해서 통일하면 좋을 것 같네요 ㅎㅎ

2024-03-02 17:25 UTC, imssein commented on src/app/api/auth.ts
> +const signUp = async (authData: LoginFormValues): Promise<any> => {
반환타입을 `Promise<any>`대신 구체적인 타입을 지정해주면 좋을 것 같습니다!

2024-03-07 16:19 UTC, oridori2705 approved these changes

2024-03-08 03:35 UTC, hj9118 approved these changes

2024-03-08 03:36 UTC, merged